name: Update NeetCode Progress

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14.5"

      - name: Run Update Script
        run: python3 update_readme.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md

          # This line checks if there are actually changes to avoid crashing
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update progress bar" && git push)
